In [2]:
import pandas as pd
import torch
from torch import nn
from torch.utils.data import DataLoader,Dataset,random_split
import torchvision as tv
import numpy as np
from PIL import Image
import os
import numpy as np
import matplotlib.pyplot as plt

import glob as gb

In [3]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.jso

chmod: cannot access '/root/.kaggle/kaggle.jso': No such file or directory


In [4]:
!kaggle datasets download -d mlg-ulb/creditcardfraud

Dataset URL: https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud
License(s): DbCL-1.0
  0% 0.00/66.0M [00:00<?, ?B/s]
100% 66.0M/66.0M [00:00<00:00, 1.74GB/s]


In [5]:
!unzip creditcardfraud.zip

Archive:  creditcardfraud.zip
  inflating: creditcard.csv          


In [6]:
device=torch.device('cuda' if torch.cuda.is_available() else "cpu")
print(device)

cuda


In [7]:
df=pd.read_csv("/content/creditcard.csv")
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [10]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [11]:
x

array([[ 0.00000000e+00, -1.35980713e+00, -7.27811733e-02, ...,
         1.33558377e-01, -2.10530535e-02,  1.49620000e+02],
       [ 0.00000000e+00,  1.19185711e+00,  2.66150712e-01, ...,
        -8.98309914e-03,  1.47241692e-02,  2.69000000e+00],
       [ 1.00000000e+00, -1.35835406e+00, -1.34016307e+00, ...,
        -5.53527940e-02, -5.97518406e-02,  3.78660000e+02],
       ...,
       [ 1.72788000e+05,  1.91956501e+00, -3.01253846e-01, ...,
         4.45477214e-03, -2.65608286e-02,  6.78800000e+01],
       [ 1.72788000e+05, -2.40440050e-01,  5.30482513e-01, ...,
         1.08820735e-01,  1.04532821e-01,  1.00000000e+01],
       [ 1.72792000e+05, -5.33412522e-01, -1.89733337e-01, ...,
        -2.41530880e-03,  1.36489143e-02,  2.17000000e+02]])

In [12]:
y

array([0, 0, 0, ..., 0, 0, 0])

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.2)
x_train

array([[ 1.43352000e+05,  1.95504092e+00, -3.80782711e-01, ...,
         4.51682478e-02, -4.71447917e-02,  9.99000000e+00],
       [ 1.17173000e+05, -4.00975239e-01, -6.26942769e-01, ...,
        -3.70468822e-01, -1.44791686e-01,  4.59000000e+01],
       [ 1.49565000e+05,  7.25090164e-02,  8.20565650e-01, ...,
         2.06394866e-01,  7.02877702e-02,  1.19900000e+01],
       ...,
       [ 7.97950000e+04, -1.46608925e-01,  9.92946123e-01, ...,
        -1.21139194e-01, -1.96195328e-01,  3.94000000e+00],
       [ 8.79310000e+04, -2.94863809e+00,  2.35484929e+00, ...,
         4.96912107e-01,  3.35821632e-01,  1.00000000e+00],
       [ 7.63810000e+04,  1.23317435e+00, -7.84850501e-01, ...,
         1.21657270e-03,  3.85878912e-02,  1.13000000e+02]])

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
sc.fit_transform(x_train)
sc.transform(x_test)

array([[-1.122118  , -8.43953559,  5.18252006, ..., -5.02350367,
        -3.16294175,  1.0815138 ],
       [-1.06408273,  0.1730534 , -1.65602032, ...,  0.10210496,
         0.30863538,  1.69317258],
       [-1.24890694,  0.71421679, -0.35634288, ...,  0.02847206,
         0.013272  , -0.22547388],
       ...,
       [ 1.00442384,  0.02018331, -0.06601034, ...,  0.89063984,
         1.0738269 , -0.31714621],
       [-0.75040591, -0.25325795,  0.59873588, ...,  0.10094377,
        -0.81883767, -0.33299371],
       [-0.96715373, -0.81263064,  0.59930001, ...,  0.31303049,
        -1.8421089 ,  3.2080607 ]])

In [15]:
df["Class"].nunique()

2

In [17]:
x_train.shape

(227845, 30)

In [46]:
class CustomDataset(Dataset):
  def __init__(self,features,labels):

    self.features=features
    self.labels=labels

  def __len__(self):
    return len(self.labels)
  def __getitem__(self,idx):
     x = torch.tensor(self.features[idx], dtype=torch.float32)
     y = torch.tensor(self.labels[idx], dtype=torch.long)
     return x,y

In [47]:
train_ds=CustomDataset(x_train,y_train)
test_ds=CustomDataset(x_test,y_test)


In [56]:
train=DataLoader(
    train_ds,
    batch_size=32,
    shuffle=True,
    pin_memory=True
)
test=DataLoader(
    test_ds,
    batch_size=32,
    shuffle=False,
    pin_memory=True
)

In [57]:
class MYNN(nn.Module):
  def __init__(self,num_features):
    super().__init__()
    self.model=nn.Sequential(
        nn.Linear(num_features,128),

        nn.BatchNorm1d(128),
        nn.ReLU(),
        nn.Dropout(0.2),
        nn.Linear(128,64),

        nn.BatchNorm1d(64),
        nn.ReLU(),
        nn.Dropout(0.2),
        nn.Linear(64,2),



    )

  def forward(self,x):
    return self.model(x)

In [59]:
epochs=100
learning_rate=0.1
model=MYNN(x_train.shape[1])
model.to(device)
criterion=nn.CrossEntropyLoss()
optim=torch.optim.Adam(model.parameters(),lr=learning_rate)

In [60]:
!pip install torchinfo
from torchinfo import summary

In [61]:
summary(model,input_size=(32,x_train.shape[1]))

Layer (type:depth-idx)                   Output Shape              Param #
MYNN                                     [32, 2]                   --
├─Sequential: 1-1                        [32, 2]                   --
│    └─Linear: 2-1                       [32, 128]                 3,968
│    └─BatchNorm1d: 2-2                  [32, 128]                 256
│    └─ReLU: 2-3                         [32, 128]                 --
│    └─Dropout: 2-4                      [32, 128]                 --
│    └─Linear: 2-5                       [32, 64]                  8,256
│    └─BatchNorm1d: 2-6                  [32, 64]                  128
│    └─ReLU: 2-7                         [32, 64]                  --
│    └─Dropout: 2-8                      [32, 64]                  --
│    └─Linear: 2-9                       [32, 2]                   130
Total params: 12,738
Trainable params: 12,738
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.41
Input size (MB): 0.00
Forward/backwa

In [62]:
from tqdm import tqdm

In [65]:
for epoch in range(epochs):

 model.train()
 total_loss=0
 correct=0
 total=0
 for x,y in tqdm (train,desc=f"epoch={epoch+1}"):
    x,y=x.to(device),y.to(device)
    output=model(x)
    loss=criterion(output,y)
    optim.zero_grad()
    loss.backward()
    optim.step()
    preds = output.argmax(dim=1)
    correct += (preds == y).sum().item()
    total += y.size(0)
    total_loss+=loss.item()
 print(f"epoch;{epoch+1},Loss:{total_loss/len(train)}")


epoch=1: 100%|██████████| 7121/7121 [00:19<00:00, 363.19it/s]


epoch;1,Loss:0.013150730486391201


epoch=2: 100%|██████████| 7121/7121 [00:20<00:00, 354.58it/s]


epoch;2,Loss:0.01356286367788167


epoch=3: 100%|██████████| 7121/7121 [00:19<00:00, 356.79it/s]


epoch;3,Loss:0.013075455065797905


epoch=4: 100%|██████████| 7121/7121 [00:21<00:00, 334.75it/s]


epoch;4,Loss:0.013053291115629181


epoch=5: 100%|██████████| 7121/7121 [00:20<00:00, 355.13it/s]


epoch;5,Loss:0.013114210853133652


epoch=6: 100%|██████████| 7121/7121 [00:19<00:00, 356.85it/s]


epoch;6,Loss:0.013080102892820867


epoch=7: 100%|██████████| 7121/7121 [00:19<00:00, 362.75it/s]


epoch;7,Loss:0.013079735452367515


epoch=8: 100%|██████████| 7121/7121 [00:21<00:00, 334.23it/s]


epoch;8,Loss:0.013023567266668729


epoch=9: 100%|██████████| 7121/7121 [00:19<00:00, 358.57it/s]


epoch;9,Loss:0.016797142916321176


epoch=10: 100%|██████████| 7121/7121 [00:19<00:00, 362.08it/s]


epoch;10,Loss:0.014956667354565866


epoch=11: 100%|██████████| 7121/7121 [00:20<00:00, 354.22it/s]


epoch;11,Loss:0.013073271625297977


epoch=12: 100%|██████████| 7121/7121 [00:19<00:00, 364.95it/s]


epoch;12,Loss:0.01305182522022348


epoch=13: 100%|██████████| 7121/7121 [00:19<00:00, 357.29it/s]


epoch;13,Loss:0.013072540200639731


epoch=14: 100%|██████████| 7121/7121 [00:20<00:00, 355.99it/s]


epoch;14,Loss:0.016735195447708583


epoch=15: 100%|██████████| 7121/7121 [00:19<00:00, 363.36it/s]


epoch;15,Loss:0.013107480831428438


epoch=16: 100%|██████████| 7121/7121 [00:20<00:00, 354.00it/s]


epoch;16,Loss:0.013122119753716632


epoch=17: 100%|██████████| 7121/7121 [00:20<00:00, 354.62it/s]


epoch;17,Loss:0.013082036745577636


epoch=18: 100%|██████████| 7121/7121 [00:19<00:00, 366.54it/s]


epoch;18,Loss:0.013170506810126825


epoch=19: 100%|██████████| 7121/7121 [00:20<00:00, 353.06it/s]


epoch;19,Loss:0.013165766613259678


epoch=20: 100%|██████████| 7121/7121 [00:19<00:00, 363.29it/s]


epoch;20,Loss:0.013502530255050538


epoch=21: 100%|██████████| 7121/7121 [00:19<00:00, 356.64it/s]


epoch;21,Loss:0.014368815070918944


epoch=22: 100%|██████████| 7121/7121 [00:20<00:00, 353.11it/s]


epoch;22,Loss:0.013112239654814513


epoch=23: 100%|██████████| 7121/7121 [00:19<00:00, 361.64it/s]


epoch;23,Loss:0.01303588886210084


epoch=24: 100%|██████████| 7121/7121 [00:20<00:00, 355.45it/s]


epoch;24,Loss:0.013080529924799588


epoch=25: 100%|██████████| 7121/7121 [00:20<00:00, 353.26it/s]


epoch;25,Loss:0.013119254254593385


epoch=26: 100%|██████████| 7121/7121 [00:19<00:00, 363.11it/s]


epoch;26,Loss:0.013054480107779461


epoch=27: 100%|██████████| 7121/7121 [00:19<00:00, 356.66it/s]


epoch;27,Loss:0.013104340768910273


epoch=28: 100%|██████████| 7121/7121 [00:19<00:00, 358.50it/s]


epoch;28,Loss:0.013132905395892115


epoch=29: 100%|██████████| 7121/7121 [00:19<00:00, 356.71it/s]


epoch;29,Loss:0.01309190074382673


epoch=30: 100%|██████████| 7121/7121 [00:20<00:00, 355.33it/s]


epoch;30,Loss:0.013077432353988326


epoch=31: 100%|██████████| 7121/7121 [00:19<00:00, 361.41it/s]


epoch;31,Loss:0.013074585644749231


epoch=32: 100%|██████████| 7121/7121 [00:20<00:00, 353.27it/s]


epoch;32,Loss:0.013098092569827758


epoch=33: 100%|██████████| 7121/7121 [00:20<00:00, 355.83it/s]


epoch;33,Loss:0.0130316750087023


epoch=34: 100%|██████████| 7121/7121 [00:19<00:00, 366.46it/s]


epoch;34,Loss:0.013105995073016066


epoch=35: 100%|██████████| 7121/7121 [00:19<00:00, 356.44it/s]


epoch;35,Loss:0.013074843925325505


epoch=36: 100%|██████████| 7121/7121 [00:19<00:00, 360.32it/s]


epoch;36,Loss:0.013107145422472691


epoch=37: 100%|██████████| 7121/7121 [00:19<00:00, 363.45it/s]


epoch;37,Loss:0.013126698254642995


epoch=38: 100%|██████████| 7121/7121 [00:19<00:00, 360.61it/s]


epoch;38,Loss:0.013108377348699105


epoch=39: 100%|██████████| 7121/7121 [00:19<00:00, 366.85it/s]


epoch;39,Loss:0.013096968134240305


epoch=40: 100%|██████████| 7121/7121 [00:19<00:00, 359.43it/s]


epoch;40,Loss:0.013069903633542448


epoch=41: 100%|██████████| 7121/7121 [00:19<00:00, 357.86it/s]


epoch;41,Loss:0.013079114382306559


epoch=42: 100%|██████████| 7121/7121 [00:19<00:00, 365.96it/s]


epoch;42,Loss:0.013088985767270076


epoch=43: 100%|██████████| 7121/7121 [00:20<00:00, 355.81it/s]


epoch;43,Loss:0.013091075348033263


epoch=44: 100%|██████████| 7121/7121 [00:19<00:00, 356.81it/s]


epoch;44,Loss:0.014403263252052625


epoch=45: 100%|██████████| 7121/7121 [00:19<00:00, 365.75it/s]


epoch;45,Loss:0.01308533875619894


epoch=46: 100%|██████████| 7121/7121 [00:20<00:00, 354.99it/s]


epoch;46,Loss:0.013088961764316068


epoch=47: 100%|██████████| 7121/7121 [00:19<00:00, 356.25it/s]


epoch;47,Loss:0.013108840328776109


epoch=48: 100%|██████████| 7121/7121 [00:19<00:00, 366.28it/s]


epoch;48,Loss:0.013089031622537443


epoch=49: 100%|██████████| 7121/7121 [00:19<00:00, 356.98it/s]


epoch;49,Loss:0.013705270639141556


epoch=50: 100%|██████████| 7121/7121 [00:19<00:00, 357.60it/s]


epoch;50,Loss:0.013074456548310976


epoch=51: 100%|██████████| 7121/7121 [00:19<00:00, 367.49it/s]


epoch;51,Loss:0.013079241912034247


epoch=52: 100%|██████████| 7121/7121 [00:20<00:00, 356.02it/s]


epoch;52,Loss:0.013092041215358773


epoch=53: 100%|██████████| 7121/7121 [00:19<00:00, 360.33it/s]


epoch;53,Loss:0.013082133023991457


epoch=54: 100%|██████████| 7121/7121 [00:19<00:00, 363.45it/s]


epoch;54,Loss:0.01310862045708604


epoch=55: 100%|██████████| 7121/7121 [00:20<00:00, 355.03it/s]


epoch;55,Loss:0.012973521360472424


epoch=56: 100%|██████████| 7121/7121 [00:19<00:00, 364.45it/s]


epoch;56,Loss:0.013096775463709093


epoch=57: 100%|██████████| 7121/7121 [00:19<00:00, 359.95it/s]


epoch;57,Loss:0.013073507860934488


epoch=58: 100%|██████████| 7121/7121 [00:19<00:00, 358.86it/s]


epoch;58,Loss:0.013116986339594109


epoch=59: 100%|██████████| 7121/7121 [00:19<00:00, 369.18it/s]


epoch;59,Loss:0.013026938540703659


epoch=60: 100%|██████████| 7121/7121 [00:19<00:00, 360.82it/s]


epoch;60,Loss:0.013112787700886063


epoch=61: 100%|██████████| 7121/7121 [00:19<00:00, 359.15it/s]


epoch;61,Loss:0.013063594689052086


epoch=62: 100%|██████████| 7121/7121 [00:19<00:00, 365.97it/s]


epoch;62,Loss:0.013073263756396308


epoch=63: 100%|██████████| 7121/7121 [00:19<00:00, 358.18it/s]


epoch;63,Loss:0.013012878049347849


epoch=64: 100%|██████████| 7121/7121 [00:19<00:00, 357.19it/s]


epoch;64,Loss:0.013093929481920669


epoch=65: 100%|██████████| 7121/7121 [00:19<00:00, 365.56it/s]


epoch;65,Loss:0.013100683023174709


epoch=66: 100%|██████████| 7121/7121 [00:19<00:00, 356.86it/s]


epoch;66,Loss:0.013078133250951775


epoch=67: 100%|██████████| 7121/7121 [00:19<00:00, 364.47it/s]


epoch;67,Loss:0.013084834304148514


epoch=68: 100%|██████████| 7121/7121 [00:19<00:00, 362.29it/s]


epoch;68,Loss:0.01311251607193461


epoch=69: 100%|██████████| 7121/7121 [00:19<00:00, 357.89it/s]


epoch;69,Loss:0.013086940312707965


epoch=70: 100%|██████████| 7121/7121 [00:19<00:00, 360.93it/s]


epoch;70,Loss:0.013058307765282003


epoch=71: 100%|██████████| 7121/7121 [00:19<00:00, 358.17it/s]


epoch;71,Loss:0.013079219622623943


epoch=72: 100%|██████████| 7121/7121 [00:19<00:00, 356.67it/s]


epoch;72,Loss:0.013293998245547405


epoch=73: 100%|██████████| 7121/7121 [00:19<00:00, 369.17it/s]


epoch;73,Loss:0.013083650964022598


epoch=74: 100%|██████████| 7121/7121 [00:19<00:00, 357.13it/s]


epoch;74,Loss:0.013056331968584217


epoch=75: 100%|██████████| 7121/7121 [00:19<00:00, 356.61it/s]


epoch;75,Loss:0.013082111209438287


epoch=76: 100%|██████████| 7121/7121 [00:19<00:00, 365.01it/s]


epoch;76,Loss:0.013077356632883888


epoch=77: 100%|██████████| 7121/7121 [00:20<00:00, 355.85it/s]


epoch;77,Loss:0.013113419969073907


epoch=78: 100%|██████████| 7121/7121 [00:19<00:00, 356.21it/s]


epoch;78,Loss:0.013108964060938236


epoch=79: 100%|██████████| 7121/7121 [00:19<00:00, 368.56it/s]


epoch;79,Loss:0.013060974295866024


epoch=80: 100%|██████████| 7121/7121 [00:19<00:00, 356.76it/s]


epoch;80,Loss:0.013143062782805894


epoch=81: 100%|██████████| 7121/7121 [00:20<00:00, 355.05it/s]


epoch;81,Loss:0.013082600488933584


epoch=82: 100%|██████████| 7121/7121 [00:19<00:00, 366.85it/s]


epoch;82,Loss:0.013116476413093147


epoch=83: 100%|██████████| 7121/7121 [00:19<00:00, 357.35it/s]


epoch;83,Loss:0.013114761726026618


epoch=84: 100%|██████████| 7121/7121 [00:19<00:00, 361.07it/s]


epoch;84,Loss:0.013069035492710828


epoch=85: 100%|██████████| 7121/7121 [00:19<00:00, 363.50it/s]


epoch;85,Loss:0.013083716079938076


epoch=86: 100%|██████████| 7121/7121 [00:20<00:00, 353.13it/s]


epoch;86,Loss:0.013095415004069282


epoch=87: 100%|██████████| 7121/7121 [00:19<00:00, 362.48it/s]


epoch;87,Loss:0.013055550425180404


epoch=88: 100%|██████████| 7121/7121 [00:19<00:00, 361.90it/s]


epoch;88,Loss:0.013120773668612357


epoch=89: 100%|██████████| 7121/7121 [00:20<00:00, 356.02it/s]


epoch;89,Loss:0.013059496241118232


epoch=90: 100%|██████████| 7121/7121 [00:19<00:00, 365.25it/s]


epoch;90,Loss:0.013094298955179103


epoch=91: 100%|██████████| 7121/7121 [00:20<00:00, 355.78it/s]


epoch;91,Loss:0.013069220274360863


epoch=92: 100%|██████████| 7121/7121 [00:19<00:00, 356.54it/s]


epoch;92,Loss:0.0130986606212965


epoch=93: 100%|██████████| 7121/7121 [00:19<00:00, 362.82it/s]


epoch;93,Loss:0.013134088370681378


epoch=94: 100%|██████████| 7121/7121 [00:19<00:00, 356.45it/s]


epoch;94,Loss:0.013070181556171694


epoch=95: 100%|██████████| 7121/7121 [00:20<00:00, 354.68it/s]


epoch;95,Loss:0.013048235977638049


epoch=96: 100%|██████████| 7121/7121 [00:19<00:00, 365.59it/s]


epoch;96,Loss:0.013117534437364704


epoch=97: 100%|██████████| 7121/7121 [00:19<00:00, 357.98it/s]


epoch;97,Loss:0.013144360317023629


epoch=98: 100%|██████████| 7121/7121 [00:19<00:00, 359.59it/s]


epoch;98,Loss:0.013132503731050703


epoch=99: 100%|██████████| 7121/7121 [00:19<00:00, 371.51it/s]


epoch;99,Loss:0.013105311334546708


epoch=100: 100%|██████████| 7121/7121 [00:19<00:00, 361.45it/s]

epoch;100,Loss:0.01303852315207372


In [66]:
model.eval()

MYNN(
  (model): Sequential(
    (0): Linear(in_features=30, out_features=128, bias=True)
    (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Dropout(p=0.2, inplace=False)
    (4): Linear(in_features=128, out_features=64, bias=True)
    (5): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (6): ReLU()
    (7): Dropout(p=0.2, inplace=False)
    (8): Linear(in_features=64, out_features=2, bias=True)
  )
)

In [67]:

total=0
correct=0
with torch.no_grad():
  for batch_features,batch_labels in test:
    batch_features,batch_labels=batch_features.to(device),batch_labels.to(device)
    output= model(batch_features)
    _, predicted=torch.max(output,1)
    total=total+batch_labels.shape[0]
    correct+=(predicted==batch_labels).sum().item()
print(correct)
print("Accuracy:", correct / total)

56864
Accuracy: 0.9982795547909132
